import {Button} from "std-widgets.slint";
import { Bmk-One } from "bmk-rec-src.slint";

export component bmtlgb inherits Window {
    preferred-width: 720px;
    preferred-height: 600px;

    background: #5500ff;
    title: "Learning Slint";
    if wholeArea.pressed : mainPart := Rectangle {background: magenta;}

    property <string> userName: "Tamaratare";
    property <int> counter: 0;

    Bmk-One {
        width: parent.width / 2;
        height: parent.height / 2;
        background: touch.pressed ? #5f5f5f : #f3f3f3;

        border-radius: 50px;
        border-color: #0d0d0d;
        border-width: 5px;

        Text {
            font-size: 20px;
            font-family: "Times New Roman";
            font-weight: 600;

            text: "Hello " + userName + " [" + counter + "]";
            color: #000000;
        }

        touch := TouchArea {
            width: parent.width;
            height: parent.height;
            clicked => {
                counter = counter + 1;
            }
        }
    }

    wholeArea := TouchArea{
        width: parent.width;
        height: parent.height;
        z: -1;
    }
}