import {Button} from "std-widgets.slint";
import { Bmk-One } from "bmk-rec-src.slint";

export component bmtlgb inherits Window {
    preferred-width: 720px;
    preferred-height: 600px;

    background: #5500ff;
    title: "Learning Slint";

    property <string> userName: "Tamaratare";
    property <int> counter: 0;

    Bmk-One {
        width: parent.width / 2;
        height: parent.height / 2;
        background: touch.pressed ? #5f5f5f : #f3f3f3;
        border-radius: 50px;

        Text {
            font-size: 20px;
            font-family: "Times New Roman";
            font-weight: 600;

            text: "Hello " + userName + " [" + counter + "]";
            color: #000000;
        }

        touch := TouchArea {
            clicked => {
                counter = counter + 1;
            }
        }
    }
}